### ISSUE TITLE
Update theme

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/financialaid.uiowa.edu#4]
## Todo
- [ ] Layer in sitenow_paragraphs
- [ ] Field slideshow for clickable link
- [ ] Theme based on admissions.uiowa.edu
- [ ] Clean up staff view
- [ ] Clean up person full node display
